[command workers] small fix checkScriptParams

diff --git a/command_workers b/command_workers
--- a/command_workers
+++ b/command_workers
@@ -20,61 +20,54 @@ commandList() {
 
 checkScriptParams() {
     if [[ $(id -u) == 0 ]]; then
-      if [[ -z "$SUDO_COMMAND" ]]; then
-        zecho 'Please, use sudo'
-        exit;
+        if [[ -z "$SUDO_COMMAND" ]]; then
+            echo 'Please, use sudo'
+            exit;
         fi
     else  echo 'Please, use sudo or login as root'
-      exit 1
+        exit 1
     fi
 
-    if [ -z "$WORKERS_DIR_LIST" ]
-       then
-            echo "Empty WORKERS_DIR_LIST";
+    if [ -z "$WORKERS_DIR_LIST" ]; then
+       echo "Empty WORKERS_DIR_LIST";
        exit 1
     fi
 
-    if [ -z "$LOGFILE" ]
-       then
-            echo "Empty LOGFILE";
+    if [ -z "$LOGFILE" ]; then
+       echo "Empty LOGFILE";
        exit 1
     fi
 
-    if [ -z "$LOGFILEERROR" ]
-       then
-            echo "Empty LOGFILEERROR";
+    if [ -z "$LOGFILEERROR" ]; then
+       echo "Empty LOGFILEERROR";
        exit 1
     fi
 }
 
 startBashCommand() {
-    # check for 1st argument. Php call back. I.e. worker
-   local PROCESS_RUN=0
-   if [ -z "$1" ]
-   then
-     printf "Missing bash command as argumnet for function \n"  # Or no parameter passed.
-     exit 1
-   fi
+    if [ -z "$1" ]
+    then
+        echo "Missing worker name"  # Or no parameter passed.
+        exit 1
+    else
+        echo "Running worker $1"
+    fi
+    local processName=$1
+    echo "$processName is not running. Starting..";
+    for WORKERS_DIR in $WORKERS_DIR_LIST
+    do
+        if [[ -d "$WORKERS_DIR" ]]; then
+            if [[ -f "$WORKERS_DIR/${processName}" ]]; then
+                PROCESS_RUN=1;
+                bash "$WORKERS_DIR/${processName}" >> $WORKERS_DIR$LOGFILE$1 2>> $WORKERS_DIR$LOGFILEERROR$1 &
+                break;
+            fi
+        fi
 
-
-                echo "Starting $1..";
-                for WORKERS_DIR in $WORKERS_DIR_LIST
-                do
-                    if [[ -d "$WORKERS_DIR" ]]; then
-                        if [[ -f "$WORKERS_DIR/$1" ]]; then
-                            PROCESS_RUN=1
-                            bash "$WORKERS_DIR/$1" >> $WORKERS_DIR$LOGFILE$1 2>> $WORKERS_DIR$LOGFILEERROR$1 &
-                            break;
-                        fi
-                    fi
-                done
-
-                 if [ $PROCESS_RUN -eq 0 ]; then
-                    echo "$1 failed to start";
-                    else
-                    PROCESS_RUN=0
-                 fi
-
+        if [ $PROCESS_RUN -eq 0 ]; then
+            echo "$processName failed to start";
+        fi
+    done
 }
 
 
