[cron_workers] small fix checkScriptParams

diff --git a/cron_workers b/cron_workers
--- a/cron_workers
+++ b/cron_workers
@@ -11,28 +11,25 @@ checkScriptParams() {
     if [[ $(id -u) == 0 ]]; then
         if [[ -z "$SUDO_COMMAND" ]]; then
             echo 'Please, use sudo'
-        exit;
+            exit;
         fi
     else  echo 'Please, use sudo or login as root'
         exit 1
     fi
 
-    if [ -z "$WORKERS_DIR_LIST" ]
-       then
-            echo "Empty WORKERS_DIR_LIST";
+    if [ -z "$WORKERS_DIR_LIST" ]; then
+       echo "Empty WORKERS_DIR_LIST";
        exit 1
     fi
 
-    if [ -z "$LOGFILE" ]
-        then
-            echo "Empty LOGFILE";
-        exit 1
+    if [ -z "$LOGFILE" ]; then
+       echo "Empty LOGFILE";
+       exit 1
     fi
 
-    if [ -z "$LOGFILEERROR" ]
-        then
-            echo "Empty LOGFILEERROR";
-        exit 1
+    if [ -z "$LOGFILEERROR" ]; then
+       echo "Empty LOGFILEERROR";
+       exit 1
     fi
 }
 
